sudo: required

language: c

compiler:
  # - clang
  - gcc

addons:
  apt:
    packages:
    - cmake
    - time

script:
  - git clone https://github.com/edenhill/librdkafka.git
  - cd librdkafka
  - ./configure
  - make
  - sudo make install