sudo: required

language: c

# compiler:
#   - gcc
  # - clang

addons:
  apt:
    packages:
    - build-essential
    - libpthread-stubs0-dev
    - zlib1g-dev
    - libssl-dev
    - libsasl2-dev
    - gcc-multilib
    - librdkafka-dev

before_install:
  - curl http://apache.rediris.es/kafka/2.0.0/kafka_2.12-2.0.0.tgz
  - tar -xzf kafka_2.11-2.0.0.tgz
  - cd kafka_2.11-2.0.0
  - ./bin/zookeeper-server-start.sh config/zookeeper.properties
  - ./bin/kafka-server-start.sh config/server.properties
  # Build librdkafka
  # - git clone https://github.com/edenhill/librdkafka.git
  # - cd librdkafka
  # - ./configure
  # - make
  # - sudo make install
  #
  # Build and install kdb+ to Apache Kafka adapter
  - git clone https://github.com/KxSystems/kafka.git
  - cd kafka
  - make
  - make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib

script:
  - echo "All DONE!!"
  # Start producer
  # - q) \l test_producer.q
  # - q) \t 1000
  # Start consumer
  # - q) \l test_consumer.q