# Please define GH_TOKEN, to access FINOS tooling repo

sudo: required

language: c

# compiler:
#   - gcc
#   - clang

addons:
  apt:
    packages:
    - build-essential
    - libpthread-stubs0-dev
    - zlib1g-dev
    - libssl-dev
    - libsasl2-dev
    - gcc-multilib
    - librdkafka-dev
    - libc6-i386

before_install:
  - sudo find / -type d -name "include"
  - ./before_install.sh

script:
  - echo "All DONE!! Current folder is ${PWD}"
  # Start producer
  - q \l test_producer.q
  - q \t 1000
  # Start consumer
  - q \l test_consumer.q