# Please define GH_TOKEN, to access FINOS tooling repo

sudo: required

language: c

# compiler:
#   - gcc
  # - clang

addons:
  apt:
    packages:
    - build-essential
    - libpthread-stubs0-dev
    - zlib1g-dev
    - libssl-dev
    - libsasl2-dev
    - gcc-multilib
    - librdkafka-dev
    - libc6-i386

before_install:
  # Install and run Kafka with Zookeeper
  - curl -O http://apache.rediris.es/kafka/2.0.0/kafka_2.12-2.0.0.tgz
  - tar -xzf kafka_2.11-2.0.0.tgz
  - cd kafka_2.11-2.0.0
  - ./bin/zookeeper-server-start.sh config/zookeeper.properties
  - ./bin/kafka-server-start.sh config/server.properties
  # Build and install kdb+ to Apache Kafka adapter
  - git clone https://github.com/KxSystems/kafka.git
  - cd kafka
  - make
  - make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
  # Download other tools needed
  - FILE="https://api.github.com/repos/finos/tooling/contents/archive.zip"
  - >
    curl -O --header 'Authorization: token $GH_TOKEN'
     --header 'Accept: application/vnd.github.v3.raw'
     --remote-name
     --location $FILE
  - unzip archive.zip
  - export PATH=$PATH:${PWD}/l64

script:
  - echo "All DONE!! Current folder is ${PWD}"
  # Start producer
  - q \l test_producer.q
  - q \t 1000
  # Start consumer
  - q \l test_consumer.q