sudo: required

language: c

# compiler:
#   - gcc
  # - clang

addons:
  apt:
    packages:
    - build-essential
    - pthreads
    - zlib-dev
    - libssl-dev
    - libsasl2-dev

script:
  - git clone https://github.com/edenhill/librdkafka.git
  - cd librdkafka
  - ./configure
  - make
  - sudo make install